### ISSUE TITLE
Cleanup artifacts

### ISSUE THREAD

**Issue by FnuGk** [firecow/gitlab-ci-local#73]
Add a flag like `--clean` that removes generated artifacts. Bonus points if you can give it at stage/job and only clean artifacts from that job.

**Comment by firecow** [comment]
By artifacts, you mean folders specified in the actual runner yaml, not the "log and include artifacts" generated in .gitlab-ci-local folder right ? @FnuGk

**Comment by FnuGk** [comment]
yep folders/files specified in the actual .gitlab-ci.yml

**Comment by firecow** [comment]
Until this feature is implemented `git clean -e "/.idea" -fdx` can be used, just be careful if you have a tendency to not use `git add`

**Comment by bcouetil** [comment]
I would like that too, please :smile: 

It would be good if generated artifacts were in a folder under .gitlab-ci-local. On top of that, a contextual folder changing between launches. Because for now for now artifacts are shared between pipelines.

**Comment by bcouetil** [comment]
@firecow the problem is bigger than I expected.

In some of my use cases, a root folder content is deeply changed by a job and passed as artifacts to downstream jobs.

It is not a matter of cleaning artifacts, but permanently changing files locally that should not be changed.

I understand that, for now, it is an easy way to have artifacts in downstream jobs without any copy needed, but I have no workaround for this in these particular use cases. I can't easily do a `git reset` between each launch for these files, since I have some of them with ongoing modification.

**Comment by bcouetil** [comment]
Created the PR #121

**Comment by firecow** [comment]
Yeah, its impossible to guess, if artifacts are deleteable or not.
I think my best advice is to use `git clean -fdx -e .idea` manually.
